baseURL = 'https://kingdomduels.com/'
languageCode = 'en-us'
title = 'Kingdom Duels'
theme = 'hugo-theme-stack'

[params]
    timeZone = 'Antarctica/Rothera'
    mainSections = ['post','story']
    favicon = '/favicon.ico'
    # LEFT SIDEBAR
    [params.sidebar]
        compact = false
        subtitle = ''
        [params.sidebar.avatar]
            enable = true
            local = true
            src = 'img/avatar.png'
    # RIGHT SIDEBAR - WIDGETS
    [params.colorScheme]
        toggle = false
    [[params.widgets.homepage]]
        type = "search"
    [[params.widgets.homepage]]
        type = "archives"
        [params.widgets.homepage.params]
            limit = 5
    [[params.widgets.homepage]]
    type = "categories"
        [params.widgets.homepage.params]
            limit = 10
    [[params.widgets.homepage]]
        type = "tag-cloud"
        [params.widgets.homepage.params]
            limit = 10
    [[params.widgets.page]]
        type = "toc"
    # FOOTER
    [params.footer]
        since = 2014
        customText = "This website is not endorsed by or affiliated with 4K Media or Konami Digital Entertainment."

[pagination]
    pagerSize = 7

[menus]
    # MAIN MENU
    [[menus.main]]
        name = 'Home'
        url = '/'
        weight = 1
    [[menus.main]]
        name = 'Deckbuilder'
        url = '/deckbuilder/'
        weight = 40
        #[menus.main.params]
            #newTab = true

    # SOCIAL MENU
    [[menus.social]]
        name = 'Discord'
        url = 'https://discord.gg/mn29q7qah4'
        weight = 10
        [menus.social.params]
            icon = "brand-discord"
            newTab = true
    [[menus.social]]
        name = 'Youtube'
        url = 'https://www.youtube.com/@kingdomduels'
        weight = 20
        [menus.social.params]
            icon = "brand-youtube"
            newTab = true
    [[menus.social]]
        name = 'Steam (Tabletop Simulator)'
        url = 'https://steamcommunity.com/sharedfiles/filedetails/?id=2884430004'
        weight = 30
        [menus.social.params]
            icon = "brand-steam"
            newTab = true
    [[menus.social]]
        name = 'Reddit'
        url = 'https://www.reddit.com/r/TheDuelistKingdom/'
        weight = 40
        [menus.social.params]
            icon = "messages1"
            newTab = true


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
